# Generated by Django 2.2.2 on 2019-06-27 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PensionFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('eligible_for_social_security', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='pensions.PensionFund')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('years_of_service', models.IntegerField()),
                ('final_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pensions.Benefit')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_liability', models.DecimalField(decimal_places=2, max_digits=20)),
                ('assets', models.DecimalField(decimal_places=2, max_digits=20)),
                ('employer_contribution', models.DecimalField(decimal_places=2, max_digits=20)),
                ('employer_normal_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_reports', to='pensions.PensionFund')),
            ],
        ),
    ]
