# Generated by Django 2.2.2 on 2019-07-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0001_initial_sketch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensionfund',
            name='data_year',
        ),
        migrations.RemoveField(
            model_name='pensionfund',
            name='eligible_for_social_security',
        ),
        migrations.AddField(
            model_name='annualreport',
            name='data_year',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annualreport',
            name='eligible_for_social_security',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annualreport',
            name='reporting_period',
            field=models.CharField(choices=[('CALENDAR', 'Calendar year'), ('FISCAL', 'Fiscal year')], default='CALENDAR', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benefit',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
