# Generated by Django 2.2.2 on 2019-08-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0004_add_fundtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='full_name',
            field=models.CharField(default='placeholder', max_length=512),
            preserve_default=False,
        ),
    ]
