# Generated by Django 2.2.2 on 2020-07-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0005_add_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='years_of_service',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
